### ISSUE TITLE
The deviceStateIndicator is created after the first updateFromMatchMedia is triggered

### ISSUE THREAD

**Issue by larsvanbraam** [mediamonks/seng-device-state-tracker#3]
This means you will first have to resize your browser before label is updated!

![image](https://user-images.githubusercontent.com/5783689/31820881-733df6b6-b5a3-11e7-919c-4a4203f241c3.png)

**Comment by jesse-mm** [comment]
@larsvanbraam This update also affect seng-disposable and seng-event in someway will be published if PR's are merged for those as well.

**Comment by jesse-mm** [comment]
@larsvanbraam fixed in latest release (1.0.6)
