### ISSUE TITLE
Change default label position

### ISSUE THREAD

**Issue by larsvanbraam** [mediamonks/seng-device-state-tracker#4]
Currently the default debug label position is the top right corner but in Chrome when you resize your window with the dev tools open you can see the window size on top of the debug label which makes it hard to read. 

![image](https://user-images.githubusercontent.com/5783689/37391239-dfc60920-276a-11e8-94bc-08fd545b2d42.png)

Currently I overwrite the default styling to move it to the bottom right corner but maybe we want this by default?

**Comment by jesse-mm** [comment]
Yes we want this configurable I think; SO TL, TR, BL, BR and default it to BL or something?

Or maybe a an option to pass an object to overwrite defaults. For example

```
debugLabelCss: {
   top: 0,
   left: 0,
}
```
